# Generated by Django 4.0.6 on 2022-07-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstypes',
            name='users_type',
            field=models.CharField(max_length=32),
        ),
    ]
