# Generated by Django 4.0.6 on 2022-07-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_userstypes_users_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['login'], name='users_login_eda8f4_idx'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
