# Generated by Django 4.0.6 on 2022-07-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_users_users_login_eda8f4_idx_alter_users_table'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='users',
            name='users_login_eda8f4_idx',
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(help_text='User login', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(help_text='User name', max_length=32),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
