# Generated by Django 4.0.6 on 2022-07-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_users_users_login_eda8f4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('users_id', 'news_id', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'category_id')},
        ),
    ]
