# Generated by Django 4.0.6 on 2022-07-30 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_alter_news_title_alter_comments_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='hashed_password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_type_id',
        ),
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UsersTypes',
        ),
    ]
