# Generated by Django 4.0.6 on 2022-08-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_comments_news_id_alter_comments_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
    ]
