# Generated by Django 4.0.6 on 2022-08-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_category_id_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user_id',
            new_name='user',
        ),
    ]
