# Generated by Django 4.0.6 on 2022-08-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_user_id_news_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='news_id',
            new_name='news',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='users_id',
            new_name='users',
        ),
    ]
